version: "3.0"
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3500:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=
    volumes:
      - ./mysql-data:/var/lib/mysql
  laravel:
    image: bitnami/laravel:10
    ports:
      - "8000:8000"
      - "5173:5173"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=
      - DB_PASSWORD=
      - DB_DATABASE=
    volumes:
      - "./rais:/app"
    depends_on:
      - mysql
  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - "./minio:/data"
    environment:
      - MINIO_ROOT_USER=
      - MINIO_ROOT_PASSWORD=
    command: minio server /data --console-address ":9090"
